# Generated by Django 4.2.6 on 2023-11-08 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('title', models.CharField(max_length=500)),
                ('artista', models.CharField(max_length=50)),
                ('album', models.CharField(max_length=50)),
            ],
        ),
    ]
