# Generated by Django 5.1.2 on 2024-10-30 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('title', models.CharField(max_length=500)),
                ('artista', models.CharField(max_length=50)),
                ('album', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=100)),
                ('duration', models.DurationField()),
            ],
        ),
        migrations.DeleteModel(
            name='Musica',
        ),
    ]
